EM-1119: React IPE
cortex-cms/cortex-snippets-client-ruby pull request #27
Opened 2017-03-20 20:53 UTC by MKwenhua

**Purpose:** To be able to pass cortex snippets to React components I created a new method on the `Snippets` module to just fetch the content. 

**JIRA:**  [EM-1119](https://cb-content-enablement.atlassian.net/browse/EM-1119)

**Changes:**
* Changes to setup
  * n/a

* Architectural changes
  * none

* Migrations
  * none
  
* Library changes
  * n/a

* Side effects
  * n/a

**QA Links:**

   * DevCortex: [http://dev.admin.cbcortex.com](http://dev.admin.cbcortex.com/)
   * Page with React +  IPE: [http://web.employer-1.development.c66.me/talentstream/sourcing-technology/resume-database](http://web.employer-1.development.c66.me/talentstream/sourcing-technology/resume-database)

**How to Verify These Changes**
* Specific pages to visit
  * `/talentstream/sourcing-technology/resume-database`

* Steps to take
  * first go to dev cortex: [http://dev.admin.cbcortex.com](http://dev.admin.cbcortex.com/) and go to webpages and click **edit** for _resume database_ .
  * change the text with the buy box component and save. Check to see if the changes show up on the search page:  [http://web.employer-1.development.c66.me/talentstream/sourcing-technology/resume-database](http://web.employer-1.development.c66.me/talentstream/sourcing-technology/resume-database)

* Responsive considerations
  * n/a

**Relevant PRs/Dependencies:**

**Additional Information**

2017-03-20 20:57 UTC, toastercup requested changes

2017-03-20 20:57 UTC, toastercup commented on lib/cortex/snippets/client.rb
> +      def snippet_content(request, options = {}, content)
This seems to share a lot of logic with the `snippet` method - do you think you could abstract the common logic to a private method, or use this method in the `snippet` method, to DRY things up a bit?

2017-03-21 20:54 UTC, MKwenhua commented on lib/cortex/snippets/client.rb
> +      def snippet_content(request, options = {}, content)
Agreed I am closing this PR since I created a `Snippet` component to take in whatever the `snippet` methods returns.

2017-03-21 20:55 UTC, MKwenhua commented
Closing this PR since I have changed the implementation on the React IPE story.

2017-03-21 20:55 UTC, closed without merging